version: '3'
services:
  appseed-app:
    restart: always
    network_mode: "host"
    env_file: .env
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./app:/app
      - ./migrations:/migrations
